### ISSUE TITLE
problème recherche ville "Paris"

### ISSUE THREAD

**Issue by CamilleBoittin** [pobsteta/cbgf-sime#3]
quand je tente de rentrer une adresse qui est à Paris, tryton ne la trouve pas ! lol
voici le test
et j'ajoute qu'il serait chouette que quand on recherche une ville, il propose parfois plusieurs noms identiques de villes dans la liste déroulante et il est dur de savoir laquelle correspond au département recherché. peut être si on peut rajouter sur la ligne d'affichage dans la liste déroulante un "- numéro de dept" ça permettrait de directement choisir le bon nom.

![170901_bug_ville_recherche_paris](https://user-images.githubusercontent.com/28709046/29975307-27e35ac8-8f36-11e7-8607-d2c5b93f0b7c.png)

**Comment by pobsteta** [comment]
le filtre et de type booléen, tu peux ajouter autant d'attributs que tu 
veux ou les mélager, clic sur le bouton Filtrer et tu comprendras ! Si 
souci appelle-moi !

@+

**Comment by CamilleBoittin** [comment]
oui génial la recherche multiple !

par contre Paris n’existe pas….


@+
Camille
03 85 40 98 54

**Comment by pobsteta** [comment]
normalement si, quel arrondissement ?

@+

**Comment by pobsteta** [comment]
Il me semble que ce ticket peut-être clos ?
